SPA/Models/LanguageLabelDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SPA.Models
{
    public class LanguageLabelDetails
    {
        public int Lang_id { get; set; }
        public string Value { get; set; }
        public string Page_Name { get; set; }
        public Nullable<int> Order_id { get; set; }
        public string English_Label { get; set; }
        public string Label_Name { get; set; }
        public string languageCulture { get; set; }
        public int? checkId { get; set; }
    }
    public class LanguageNewShop
    {
        public int Lang_id { get; set; }
        public string Value { get; set; }
        public string Page_Name { get; set; }
        public Nullable<long> Order_id { get; set; }
        public string English_Label { get; set; }
        public string SubPage { get; set;}
        public string Catg_Sep { get; set; }

    }
    public class ShopDetails
    {
        public int? LangId { get; set; }
        public int? Display_FreeCustomer { get; set;}
        public string Currency { get; set;}
    }
}

SPA/Controllers/ShopController.cs
using Newtonsoft.Json.Linq;
using SPA.Common;
using SPA.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SPA.Controllers
{
    [checkShop]
    public class ShopController : Controller
    {
        int schlId = Convert.ToInt32(ConfigurationManager.AppSettings["ApplicationVariable"]);
        // GET: Employee
        cctspDatabaseEntities22 SPA = new cctspDatabaseEntities22();
        CultureInfo enGB = new CultureInfo("en-GB");
        Function fu = new Function();
        PuchSMS Sms = new PuchSMS();
        PushEmail Email = new PushEmail();
        JavaScriptSerializer js = new JavaScriptSerializer();
        Sql sql = new Sql();
        string link = System.Web.HttpContext.Current.Request.Url.Host;
        public ShopController()
        {
            schlId = Convert.ToInt32(fu.GetShopId(link));
        }
        // GET: Shop
        [CustomAutohrize(null)]
        public ActionResult Shop()
        {
            try
            {
                //if (Convert.ToInt32(Session["RoleId"].ToString()) != 4 && Convert.ToInt32(Session["RoleId"].ToString()) > 0)
                //{
                var ShopInfo = SPA.CCTSP_LendingPageMaster.Where(c => c.Schid == schlId).Select(c => new Models.ShopMasterDetail
                {
                    Lang_id = c.CCTSP_SchoolMaster.Lang_id,
                    Display_FreeCustomer = c.CCTSP_SchoolMaster.Display_FreeCustomer,
                    Display_Invoice = c.CCTSP_SchoolMaster.Display_Invoice,
                    DisplayMarketing = c.Display_Marketing,
                    BookingApproval = c.CCTSP_SchoolMaster.BookingApproval,
                    SchlWebsite = c.CCTSP_SchoolMaster.SchlWebsite,
                    Flow_Id=c.CCTSP_SchoolMaster.Flow_Id
                }).FirstOrDefault();
                ViewBag.Language = SPA.Language_Label_Detail.Where(c => c.Page_Name == "Shop_Tab" && c.Lang_id == ShopInfo.Lang_id && c.ActiveStatus == "A").Select(c => new Models.LanguageLabelDetails
                {
                    Lang_id = c.Lang_id,
                    English_Label = c.English_Label,
                    Page_Name = c.Page_Name,
                    Order_id = c.Order_id,
                    Value = c.Value
                }).ToList();
                ViewBag.Title = SPA.Language_Label_Detail.Where(c => c.Page_Name == "Title" && c.Order_id == 8 && c.Lang_id == ShopInfo.Lang_id).Select(c => c.Value).FirstOrDefault();
                ViewBag.Schlid = schlId;
                var MTab = SPA.CCTSP_LendingPageMaster.Where(c => c.Schid == schlId).Select(c => c.Display_Marketing).FirstOrDefault();
                ViewBag.DisplayTab = MTab;
                ViewBag.SubMenu = fu.AccessSubMenu(ShopInfo.Lang_id.Value, Convert.ToInt32(Session["RoleId"].ToString()), "Shop_Tab",ShopInfo.Flow_Id);
                List<Models.ConditionList> ConditionList = new List<Models.ConditionList>();
                //Models.ConditionList Condition = new ConditionList();
                //Condition.Condition = "Language";
                //Condition.ConditionValue = schlId == 251 || schlId == 273 ? "YES" : "NO";
                //ConditionList.Add(Condition);
                //Condition = new Models.ConditionList();
                //Condition.Condition = "Marketing";
                //Condition.ConditionValue = MTab == "1" ? "YES" : "NO";
                //ConditionList.Add(Condition);
                //Condition = new Models.ConditionList();
                //Condition.Condition = "Payment";
                //Condition.ConditionValue = schlId == 254 || schlId == 257 ? "YES" : "NO";
                //ConditionList.Add(Condition);
                ViewBag.ConditionList = fu.LayoutCondition(ShopInfo); ;
                return View();
                //}
                //else
                //    return RedirectToAction("SignIn", "Login");
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
        [CustomAutohrize(null)]
        public ActionResult ShopOwnerSetup()
        {
            try
            {
                Response.Cache.SetCacheability(HttpCacheability.NoCache);
                Response.Cache.SetExpires(DateTime.Now);
                Response.Cache.SetNoServerCaching();
                Response.Cache.SetNoStore();
                Response.Cookies.Clear();
                Request.Cookies.Clear();
                //if (Convert.ToInt32(Session["RoleId"].ToString()) != 4)
                //{
                string ShopDetails = "SELECT a.SchlName as SHOPNAME,a.Lang_id as LangId,a.latitude,a.longitude, " +
                                     "a.location as Location,c.ShopDesc, a.Schlid as ShopId, d.CatgTypeId as MainCatgId, " +
                                     "e.SolutionId as ShopTypeId,d.CatgDesc as MAINCATEGORY,e.SectionName as SHOPTYPE,b.Gender as TITLE, " +
                                     "b.firstname as OWNERNAME,b.Lastname as OWNERSURNAME,b.Phoneno as MOBILENUMBER, a.SchlCity as CITY ,  " +
                                     "a.SchPin as ZIPCODE,a.SchlEmail as ShopEmail,b.EmailId as OwnerEmail,a.SchlAddress as ADDRESS ,  " +
                                     "a.ImageLogo as ImageLogo,a.SchlWebsite as ShopWebsite,a.BANKNAME ,a.BANKACCOUNT,a.IBANNO " +
                                     ",b.Salutation as SALUTATION,b.PasswordQuerry2 as LANDLINENUMBER,b.[state] as State," +
                                     "b.GLN_No as GLN_NO,b.ZSR_No as ZSR_NO,b.Title as GENDER,a.Vat as VAT,a.VatNumber as VATNUMBER," +
                                     "a.Currency as Currency,a.OverDue as PaymentDuration,a.Extend_Pay_Duration as ExtendDuration,a.street, "+
                                     "a.streetNumber,a.Display_Invoice,a.Invoice_FreeText as InvoiceFreeText,a.SchCountry as Country,a.SchlStudentStrength,a.Flow_Id as Flow_Id " +
                                     ", InvoiceEmailTxt = Case When a.Invoice_Email_Txt != '' then a.Invoice_Email_Txt else f.value end "+
                                     "FROM cctsp_Schoolmaster a " +
                                     "JOIN cctsp_User b on a.Schlid = b.schid  " +
                                     "JOIN CCTSP_LendingPageMaster c on c.Schid = a.Schlid " +
                                     "JOIN CCTSP_CategoryDetails d on d.CatgTypeId = a.MainCategory " +
                                     "JOIN ctsp_SolutionMaster e on e.SolutionId = convert(bigint, a.ShopType) " +
                                     "LEFT JOIN Language_Label_Detail f on f.Lang_Id=a.Lang_Id and f.ActiveStatus='A' and f.Page_Name='Shop_Owner_Text' and f.Order_Id=29 "+
                                     "WHERE a.Schlid = " + schlId + " and b.RoleId = 1 and a.ActiveStatus = 'A' and b.ActiveStatus = 'A'";
                var ShopInfo = SPA.Database.SqlQuery<Models.shopMaster>(ShopDetails).FirstOrDefault();
                ViewBag.CheckInvoice = fu.CheckInvoice(ShopInfo.Display_Invoice);
                var CatgNameList = "Salutation,New_Gender,Title";
                ViewBag.DropDownList = fu.getInvoiceCatgDetails(CatgNameList, ShopInfo.LangId.Value);
                bool TextTabAccess = true;
                if(ShopInfo.Flow_Id>1)
                    TextTabAccess = fu.CheckSubTabAccess("Texts", ShopInfo.Flow_Id.Value);
                ViewBag.TextTabAccess = TextTabAccess;
                ViewBag.ShopInfo = ShopInfo;
                ViewBag.Language = SPA.Language_Label_Detail.Where(c => c.Page_Name == "Shop_Owner_setup" && c.Lang_id == ShopInfo.LangId).Select(c => new LanguageLabelDetails { Value = c.Value, Order_id = c.Order_id, Lang_id = c.Lang_id, Page_Name = c.Page_Name }).ToList();
                //ViewBag.Title = SPA.CCTSP_CategoryDetails.Where(c => c.CatgId == 110 && c.ActiveStatus == "A" && c.Lang_Id == ShopInfo.LangId).Select(c => c.CatgType).OrderBy(c => c).ToList();
                return View();
                //}
                //else
                //{
                //    return RedirectToAction("SignIn", "Login");
                //}
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
        public ActionResult Shopschedule()
        {
            var Days = SPA.CCTSP_SchedulerMaster.Where(c => (c.ActiveStatus == "A" || c.ActiveStatus == "R") && c.SchId == schlId).OrderBy(c => c.PeriodNumber).Distinct().ToList();
            ViewBag.Language = fu.getstartandEndLangList("Create_Employee", 18, 29, Days.FirstOrDefault().CCTSP_SchoolMaster.Lang_id.Value);
            return View(Days);
        }
        public ActionResult Marketing()
        {
            var Marketingdata = SPA.Marketing_Master.Where(c => c.schId == schlId && c.ActiveStatus == "A").ToList();
            ViewBag.Marketingdata = Marketingdata;
            int LangId = SPA.CCTSP_SchoolMaster.Where(c => c.SchlId == schlId && c.ActiveStatus == "A").Select(c => c.Lang_id).FirstOrDefault().Value;
            ViewBag.language = fu.getLanguageData("Marketing_page", 0, LangId);
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public JObject MarketingAdd(Marketing_Master MM)
        {
            Marketing_Master CheckData = new Marketing_Master();
            Models.MarketingMaster EditData = new MarketingMaster();

SPA/Views/Shop/ActiveText.cshtml
@using System.Configuration
@{
    Layout = null;
    List<Language_Label_Detail> Language = ViewBag.Language;
    var item = ViewBag.Data;
    SPA.Models.getAccess getAccess = ViewBag.Access;
}
@if (item != null)
{
    if (item.ItenName == "Default")
    {
        <td class="spa-label1">@Language.Where(c => c.English_Label == item.CCTSP_CategoryDetails.CatgDesc).Select(c => c.Value).FirstOrDefault() (ST)</td>
    }
    else
    {
        <td class="spa-label1">@Language.Where(c => c.English_Label == item.CCTSP_CategoryDetails.CatgDesc).Select(c => c.Value).FirstOrDefault()</td>
    }
    string Display = "";
    if (item.CCTSP_CategoryDetails.CatgId == 120)
    {
        Display = "Email";
    }
    if (item.CCTSP_CategoryDetails.CatgId == 121)
    {
        Display = "SMS";
    }

    <td class="spa-label1 text-center">@Display</td>
        <td class="spa-label1">
            @item.SectionDesc
        </td>



                <td class="spa-label1 text-center">

                    <div class="onoffswitch DivTextActive">

                        @if (item.Group == null || item.Group == "")
                        {
                            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="@item.SolutionId" checked>
                            <label class="onoffswitch-label round" for="@item.SolutionId">
                                <span class="onoffswitch-inner">@Language.Where(c => c.Order_id==40).Select(c => c.Value).FirstOrDefault()</span>
                                <span class="onoffswitch-switch">@Language.Where(c => c.Order_id == 41).Select(c => c.Value).FirstOrDefault()</span>
                            </label>
                        }
                        else
                        {

                            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="@item.SolutionId">
                            <label class="onoffswitch-label round" for="@item.SolutionId">
                                <span class="onoffswitch-inner">@Language.Where(c => c.Order_id == 40).Select(c => c.Value).FirstOrDefault()</span>
                                <span class="onoffswitch-switch">@Language.Where(c => c.Order_id == 41).Select(c => c.Value).FirstOrDefault()</span>
                            </label>
                        }

                    </div>
                </td>

                if (item.ItenName == "Default")
                {
                    <td></td>
                }
                else
                {
                    <td class="text-center">
                        @if (((getAccess.update != "N" && (getAccess.FlowStatus == "2" || getAccess.FlowStatus == "3")) || (getAccess.FlowStatus == "1")))
                        {
                            <a onclick="EditText(@item.SolutionId);"><i class="fa fa-pencil-square-o spa-icon1" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="@Language.Where(c => c.Order_id == 30).Select(c => c.Value).FirstOrDefault()" data-original-title="" title=""></i></a>@*Delete*@
                        }
                        @if (((getAccess.Delete != "N" && (getAccess.FlowStatus == "2" || getAccess.FlowStatus == "3")) || (getAccess.FlowStatus == "1")))
                        {
                            <a onclick="DeleteText(@item.SolutionId);"><i class="fa fa-trash spa-icon1" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="@Language.Where(c => c.Order_id == 31).Select(c => c.Value).FirstOrDefault()" data-original-title="" title=""></i></a>@*Delete*@
                        }
                    </td>

                }
}


<script>
    $(".DivTextActive input").click(function () {
        $(".loader").show();
        var Id = $(this).attr("id");
        var De = "D";

        if ($(this).prop("checked")) {
           
            $.post("/Shop/DeactivateText?SolutionId=" + Id, function (data)
            {
                var soultionIdlist = data.split("~");
                for (i = 0; i < soultionIdlist.length; i++)
                {
                    var ab=soultionIdlist[i];
                    $.ajax({
                        type: 'POST',
                        url: '/Shop/ActiveText',
                        async: false,
                        traditional: true,
                        data: { SoultionIdList: ab },
                        success: function (SkillDot) {
                            $("#SkillDataspa #tr_" + ab).html(SkillDot);
                            
                        },
                        error: function (args) {
                            alert("Error");
                        }
                    })

                }
                $(".loader").hide();
               
            });
           
           
        }
        else
        {
            $.post("/Shop/DeactivateText?SolutionId=" + Id + "&status=" + De, function ( data)
            {
                $(".loader").hide();
            });
        }
    });


</script>







SPA/Views/Shop/ChangePassword.cshtml
@{
    Layout = null;
    List<Language_Label_Detail> Language = new List<Language_Label_Detail>();
    Language = ViewBag.Language;
}
<div class="create-employee-form shop-owner-setup">
    <form id="ChangePasswordForm" action="/Shop/ChangePasswordEdit" method="post">
        <div class="col-lg-14 col-lg-offset-5 col-md-16 col-md-offset-4">
            @Html.AntiForgeryToken()
            <div class="alert alert-danger" style="display: none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-lg-7 col-md-8 col-sm-7">
                    @Html.Label(@Language.Where(c => c.Order_id == 1).Select(c => c.Value).FirstOrDefault() + " *", htmlAttributes: new { @class = "form-label spa-label-bold" })
                </div>
                <div class="col-lg-17 col-md-16 col-sm-17">
                    <div class="form-group">
                        @Html.Editor("CTPASSWORD", new { htmlAttributes = new { @class = "form-control spa-text-box required", @id = "PhoneNo", @size = 10, @type = "password", @placeholder = @Language.Where(c => c.Order_id == 6).Select(c => c.Value).FirstOrDefault(), @minlength = "6", autocomplete = "off" } })
                        @Html.ValidationMessage("CTPASSWORD", "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7 col-md-8 col-sm-7">
                    @Html.Label(@Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault() + " *", htmlAttributes: new { @class = "form-label spa-label-bold" })
                </div>
                <div class="col-lg-17 col-md-16 col-sm-17">
                    <div class="form-group">
                        @Html.Editor("NWPASSWORD", new { htmlAttributes = new { @class = "form-control spa-text-box required", @id = "NWPASSWORD", @type = "password", @placeholder = @Language.Where(c => c.Order_id == 7).Select(c => c.Value).FirstOrDefault(), @minlength = "6", autocomplete = "off" } })
                        @Html.ValidationMessage("NWPASSWORD", "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7 col-md-8 col-sm-7">
                    @Html.Label(@Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault() + " *", htmlAttributes: new { @class = "form-label spa-label-bold" })
                </div>
                <div class="col-lg-17 col-md-16 col-sm-17">
                    <div class="form-group">
                        @Html.Editor("CPPASSWORD", new { htmlAttributes = new { @class = "form-control spa-text-box required", @id = "CPPASSWORD", @type = "password", @placeholder = @Language.Where(c => c.Order_id == 8).Select(c => c.Value).FirstOrDefault(), autocomplete = "off", equalto = "#NWPASSWORD" } })
                        @Html.ValidationMessage("CONFIRM PASSWORD", "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group text-right margin-top20">
                <input type="button" class="btn btn-green" value="@Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault()" onclick="SaveNewPassword();" />
                <input type="button" class="btn btn-black" id="btnPwdCancel" value="@Language.Where(c => c.Order_id == 9).Select(c => c.Value).FirstOrDefault()" />
                @*<input type="button" class="btn btn-black" onclick="GoToEmployeeMaster();" value="Cancel" hidden />*@
            </div>
        </div>
    </form>
</div>


<script>
    $("#btnPwdCancel").click(function ()
    {
        $("#ChangePasswordForm").validate().resetForm();
        $("#ChangePasswordForm")[0].reset();
    });
</script>


SPA/Views/Shop/Language_LabelDetail.cshtml
@{
    ViewBag.Title = "Language_LabelDetail";
    Layout = null;
    List<Language_Label_Detail> LabelDetail = new List<Language_Label_Detail>();
    LabelDetail = ViewBag.LanguageDetailList;
    int MaxLength = LabelDetail.Select(c => c.Order_id).Max().Value;
}

<table class="table table-striped margin-top15">
    <thead>
        <tr>
            <th class="spa-label2">English</th>
            <th class="spa-label2">German</th>
            <th class="spa-label2">French</th>
        </tr>
    </thead>
    <tbody>

        @for (int i = 1; i <= MaxLength; i++)
        {
            <tr>
                @foreach (var item in LabelDetail.Where(c => c.Order_id == i).OrderBy(c => c.Lang_id))
                {
                    if (item.Lang_id == 1)
                    {
                        <td class="spa-label1 @(item.newdata=="0"?"":"DeclinedTrColor")" style="cursor:pointer;" onclick="EditLanguage(@item.Lang_Detail_Id)">@item.Value</td>
                    }
                    if (item.Lang_id == 2)
                    {
                        <td class="spa-label1 @(item.newdata=="0"?"":"DeclinedTrColor")" style="cursor:pointer;" onclick="EditLanguage(@item.Lang_Detail_Id)">@item.Value</td>
                    }
                    if (item.Lang_id == 3)
                    {
                        <td class="spa-label1 @(item.newdata=="0"?"":"DeclinedTrColor")" style="cursor:pointer;" onclick="EditLanguage(@item.Lang_Detail_Id)">@item.Value</td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

SPA/Views/Shop/Texts.cshtml
@{
    Layout = null;
    List<Language_Label_Detail> Language = new List<Language_Label_Detail>();
    Language = ViewBag.Language;
    List<SPA.Models.TextDisplay> TextDetailsList = new List<SPA.Models.TextDisplay>();
    TextDetailsList = ViewBag.EventList;
    var TextList = TextDetailsList.Where(c => c.ItenName == "Default").Select(c => c.Catgdesc).Distinct().ToList();
    var BasicInfo = TextDetailsList.Count > 0 ? TextDetailsList.FirstOrDefault() : new SPA.Models.TextDisplay();
}
<div class="product-catalog holiday">
    <div class="margin-top15 user-details table-res-border">
        <div class="texts">
            @*<div class="col-lg-3 col-md-3 col-sm-4 margin-top5 text-right">
                    @Html.Label("Event Type", htmlAttributes: new { @class = "form-label spa-label1" })
                </div>
                <div class="col-lg-3 col-md-4 col-sm-5">
                    <div class="dropdown spa-dropdown" hidden>
                        <a class="dropdown-toggle spa-text-box form-control spa-dropdown-box" data-toggle="dropdown">
                            All
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"> All</a></li>
                            <li><a href="#"> All</a></li>
                        </ul>
                    </div>
                    @Html.ValidationMessage("", "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-2 col-md-3 col-sm-3 margin-top5 text-right">
                    @Html.Label("Media", htmlAttributes: new { @class = "form-label spa-label1" })
                </div>
                <div class="col-lg-3 col-md-4 col-sm-5">
                    <div class="dropdown spa-dropdown" hidden>
                        <a class="dropdown-toggle spa-text-box form-control spa-dropdown-box" data-toggle="dropdown">
                            All
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"> All</a></li>
                            <li><a href="#"> All</a></li>
                        </ul>
                    </div>
                    @Html.ValidationMessage("", "", new { @class = "text-danger" })
                </div>*@
            <div class="text-right">
                @if (((BasicInfo.UpdateAccess != "N" && (BasicInfo.FlowStatus == "2" || BasicInfo.FlowStatus == "3")) || (BasicInfo.FlowStatus == "1")))
                {
                    <a class="title-green16 TextTouch" id="add-vac"><i class="fa fa-plus-square margin-right5"></i> @Language.Where(c => c.Order_id == 1).Select(c => c.Value).FirstOrDefault()</a>@*Add Text*@
                }
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="choose-your-product p-relative margin-top15 border-top-grey">
            <div class="add-vacation-block BlockText">
                <form id="TextForm" action="/Shop/AddText" method="post">
                    <ul class="col-lg-20 col-lg-offset-2">
                        <li class="col-lg-12 col-md-12 col-sm-10 col-xs-24 form-group">
                            <label class="form-label spa-label1">@Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault()</label>@*EVENT TYPE*@
                            <div class="dropdown spa-dropdown">
                                <a class="dropdown-toggle spa-text-box form-control spa-dropdown-box EventDisplayDrop dropmenuEllips" data-toggle="dropdown">
                                    @if (TextList.Count > 0)
                                    {
                                        @Language.Where(c => c.English_Label == TextList.FirstOrDefault()).Select(c => c.Value).FirstOrDefault()
                                    }
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu TextEvent">
                                    @foreach (var item in TextList)
                                    {
                                        <li><a class="dropmenuEllips" id="@item">@Language.Where(c => c.English_Label == item).Select(c => c.Value).FirstOrDefault()</a></li>
                                    }
                                    @if (TextList.Count > 0)
                                    {
                                        <input type="hidden" value="@TextList.FirstOrDefault()" name="SelectedEvent" id="SelectedEvent" />
                                    }
                                    else
                                    {
                                        <input type="hidden" value="" name="SelectedEvent" id="SelectedEvent" />
                                    }
                                    @*@Html.Hidden("SelectedEvent")*@
                                    @Html.Hidden("EditUserId")
                                </ul>
                            </div>
                        </li>
                        <li class="col-lg-12 col-md-12 col-sm-14 col-xs-24 form-group">
                            <label class="form-label spa-label1">@Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault()</label>@*MEDIA*@
                            <ul class="row margin-top5">
                                <li class="col-lg-8 col-md-8 col-sm-8 col-xs-10 spa-radio">
                                    <input id="EmailId" type="radio" name="EmailId" value="EmailId" checked="checked">
                                    <label for="EmailId" class="form-label spa-label1">Email</label>
                                </li>
                                <li class="col-lg-8 col-md-8 col-sm-8 col-xs-10 spa-radio">
                                    <input id="SMSFIELD" type="radio" name="EmailId" value="SMSFIELD">
                                    <label for="SMSFIELD" class="form-label spa-label1">SMS</label>
                                </li>
                                @*<li class="col-lg-8 col-md-8 col-sm-8 spa-radio" hidden>
                                        <input id="option2" type="radio" name="field" value="option" hidden>
                                        <label for="option2" class="form-label spa-label1" hidden>Screen</label>
                                    </li>*@
                            </ul>
                        </li>
                        <li class="col-lg-24 col-lg-24 col-md-24 col-sm-24 col-xs-24 form-group pull-left">
                            <label class="form-label spa-label1">@Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault()</label>@*TEXT*@
                            <textarea type="text" class="form-control spa-text-area required" id="MsgArea" name="MsgArea" placeholder="@Language.Where(c => c.Order_id == 17).Select(c => c.Value).FirstOrDefault()"></textarea>@*Welcome back Mr.x/Ms.Y, thanks for visiting us again!*@
                        </li>
                        <div class="clearfix"></div>
                        <li class="col-lg-24 col-md-24 col-sm-24 col-xs-24 text-right">
                            <input type="button" class="btn btn-green btn-small margin-right5 width100" value="@Language.Where(c => c.Order_id == 7).Select(c => c.Value).FirstOrDefault()" onclick="AddTextToDb();"> @*save*@
                            <input type="button" class="btn btn-black btn-small width100" value="@Language.Where(c => c.Order_id == 8).Select(c => c.Value).FirstOrDefault()" id="CancelText">  @*cancel*@
                            @*<input type="button" class="btn btn-black btn-small" value="Cancel" onclick="GoToEmployeeMaster();">*@
                        </li>
                    </ul>
                </form>
            </div>
            <div id="ShopTextId">
                @Html.Action("TextsDisplay", "Shop", new { Language = Language })
            </div>

        </div>
        <div class="clearfix"></div>
    </div>
</div>
<script>

    $(".add-vac-dtl").click(function () {
        $(".add-vacation-block").slideToggle();
    });
    $("#CancelText").click(function () {
        $("#TextForm")[0].reset();
        $("#TextForm").validate().resetForm();
        $(".BlockText").slideToggle();
        $("#EditUserId").val("");
    });
    $(".TextTouch").click(function () {
        $(".BlockText").slideToggle();
    });
    $('.TextEvent li a').click(function () {
        var selText = $(this).prop("id");
        var LangText = $.trim($(this).html());
        $("#SelectedEvent").val(selText.trim());
        $(".EventDisplayDrop").html(LangText + '<span class="caret"></span>');
    });
</script>