SPA/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SPA.Common;
using SPA.Models;
using System.Configuration;

namespace SPA.Controllers
{
    [checkShop]
    public class FooterController : Controller
    {      
        int schlId = Convert.ToInt32(ConfigurationManager.AppSettings["ApplicationVariable"]);       
        cctspDatabaseEntities22 SPA = new cctspDatabaseEntities22();
        PushEmail Email = new PushEmail();
        Function fu = new Function();
        string link = System.Web.HttpContext.Current.Request.Url.Host;
        public FooterController()
        {
            schlId = Convert.ToInt32(fu.GetShopId(link));
        }
        // GET: Footer
        [HttpGet]
        public ActionResult Contact()
        {
            try
            {
                var Lang_Id = SPA.CCTSP_SchoolMaster.Where(c => c.SchlId == schlId && c.ActiveStatus == "A").Select(c=>c.Lang_id).FirstOrDefault();
                List<LanguageLabelDetails> ContactLangauge = SPA.Language_Label_Detail.Where(c => c.Page_Name == "Lending_Page" && c.Lang_id == Lang_Id && c.ActiveStatus=="A")
                    .Select(c => new LanguageLabelDetails { Lang_id = c.Lang_id, Order_id = c.Order_id, Page_Name = c.Page_Name, Value = c.Value,English_Label=c.English_Label })
                    .OrderBy(c => c.Order_id)
                    .ToList();
                ViewBag.ContactLangauge = ContactLangauge;
               // ViewBag.LanguageBack = SPA.Language_Label_Detail.Where(c => c.Page_Name == "back_button" && c.Order_id == 1 && c.Lang_id == ShopInfo.Lang_id).Select(c => c.Value).FirstOrDefault();
                return View();
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
        [HttpPost]
        public ActionResult Contact(FormCollection Get)
        {
            try
            {
                spa_contact contact = new spa_contact();
                contact.FirstName = Get["ConFirstName"].ToString();
                //contact.Street = Get["ConStreet"].ToString();
                //contact.place = Get["Conplace"].ToString();
                contact.Email = Get["ConEmail"].ToString();
               // contact.Firm = Get["ConFirm"].ToString();
                //contact.plz = Get["ConPLZ"].ToString();
                //contact.Mobile = Get["ConTelephone"].ToString();
                contact.communication = Get["ConCommunication"].ToString();
                contact.schid = schlId;
                contact.Activestatus = "A";
                SPA.spa_contact.Add(contact);
                SPA.SaveChanges();
                Email.EmailForContact(contact);
                return RedirectToAction("Home", "Home");
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
        public ActionResult PROFILE()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
        public ActionResult Links()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                fu.ErrorSend(RouteData, e);
                return RedirectToAction("Error_List", "Error");
            }
        }
    }
}

SPA/Views/Shared/ClickGoLayout.cshtml
@using SPA.Common
@{
    List<SPA.Models.LanguageNewShop> Language = ViewBag.Language;
    Language = Language.Where(c => c.Page_Name == "Layout_Header").ToList();
    int status = ViewBag.status;
    int LanguageId = ViewBag.LangId;
    Function fu = new Function();
    var LangNameList = fu.LanguageNameList();

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Make Your Personal Website as sale your service online with online Reservation functionality">
    <meta name="keywords" content="Online Booking,SPA,Doctor Service,HealthCare,TARIF 590">
    <meta name="og:region" content="männedorf">
    <meta name="og:country-name" content="Switzerland">
    <meta name="og:email" content="info@click-and-go.ch">
    <meta name="author" content="christoph glathard">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="CLICK-AND-GO" />
    @Styles.Render("~/Contents/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/clickscript")
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-106805354-1"></script>
    <script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments)};
	gtag('js', new Date());
	gtag('config', 'UA-106805354-1');
    </script>
    @if (LanguageId > 1)
    {
       @Html.Partial("_LangValidation", "/Scripts/messages_" + LangNameList.Where(c => c.Lang_id == LanguageId).Select(c => c.English_Label).FirstOrDefault().ToLower() + ".js");
    }
    <script src="~/Scripts/jquery.scrollify.min.js"></script>
    <title>CLICK-AND-GO</title>
</head>
<body>
    <div class="ClickGo_layout">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-24 col-md-24 col-sm-24">
                    <div class="language-menu">
                        <ul id="LangChange">
                            @if (status == 2)
                            {
                                foreach (var Item in LangNameList)
                                {
                                    <li id=@Item.Value><a href="?Lang=@Item.Lang_id" class="@( (LanguageId==Item.Lang_id || (LanguageId==0 && Item.Lang_id==2))? "lan-active" : "")">@Item.English_Label</a></li>
                                }
                                @*<li id="German"><a href="?Lang=2" class="@(LanguageId == 2 || LanguageId==0? "lan-active" : "")">DE</a></li>
                                    <li id="French"><a href="?Lang=3" class="@(LanguageId == 3 ? "lan-active" : "")">FR</a></li>
                                    <li id="English"><a href="?Lang=1" class="@(LanguageId == 1? "lan-active" : "")">EN</a></li>*@
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row layout_padding">
                <div class="col-lg-8 col-md-8 col-sm-10">
                    <div class="ClickGo_logo" name="Home">
                        <a id="logo" href="/ClickGo?Lang=@LanguageId#Home">
                            <img src="~/images/click/Click_icon.png" />
                            <div class="clicklogo_text">
                                <img src="~/images/click/Click_text.png" />
                                <p>@*EINFACH.SCHNELL.BEQUEM.*@ @Language.Where(c => c.Order_id == 6).Select(c => c.Value).FirstOrDefault()</p>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-16 col-md-16 col-sm-14">
                    @*<div class="right-btn">
                            <a href="javascript:void()" class="isdrag">
                                <i class="fa fa-align-justify"></i>
                            </a>
                        </div>*@
                    <div class="clickgo_menu headertop-box" id="clickgo_menu">
                        <ul class="subMenu">
                            <li name="Home" class="active" index-scroll="0"><a href="/ClickGo?Lang=@LanguageId#Home">@*HOME*@ @Language.Where(c => c.Order_id == 1).Select(c => c.Value).FirstOrDefault()</a></li>
                            <li name="Advantages" index-scroll="1"><a href="/ClickGo?Lang=@LanguageId#Advantages">@*ADVANTAGES*@ @Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault()</a></li>
                            <li name="Features" index-scroll="2"><a href="/ClickGo?Lang=@LanguageId#Features">@*FEATURES*@ @Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault()</a></li>
                            @*<li name="Prices" index-scroll="3"><a href="/ClickGo?Lang=@LanguageId#Prices">@*Prices @Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault()</a></li>*@
                            <li name="Process" index-scroll="3"><a href="/ClickGo?Lang=@LanguageId#Process">@*PROCESS*@ @Language.Where(c => c.Order_id == 10).Select(c => c.Value).FirstOrDefault()</a></li>
                            <li name="Click-and-go" index-scroll="4"><a href="/ClickGo?Lang=@LanguageId#Click-and-go">@*WHY CLICK-AND-GO*@ @Language.Where(c => c.Order_id == 11).Select(c => c.Value).FirstOrDefault()</a></li>
                            <li name="contact" index-scroll="5"><a href="/ClickGo?Lang=@LanguageId#contact">@*CONTACT US*@ @Language.Where(c => c.Order_id == 8).Select(c => c.Value).FirstOrDefault()</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="welcome-modal">
        <div id="welcome" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body margin-bottom30" id="WelcomeAlert">

                    </div>
                </div>
            </div>
        </div>
    </div>
    @RenderBody()
    @RenderSection("scripts", required: false)
    <script>

        //$(".right-btn a").click(function (event) {
        //    // lock scroll position, but retain settings for later
        //    var scrollPosition = [
        //        self.pageXOffset || document.documentElement.scrollLeft || document.body.scrollLeft,
        //        self.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop
        //    ];
        //    event.preventDefault();
        //    if ($(this).hasClass("isdrag")) {
        //        $(".headertop-box").animate({
        //            right: "0px"
        //        }, 400);
        //        $(this).removeClass("isdrag").addClass("drag-toggle");
        //        $('.blackBG').prepend('<div class="mask2"></div>');
        //        var html = jQuery('html');
        //        html.data('scroll-position', scrollPosition);
        //        html.data('previous-overflow', html.css('overflow'));
        //        html.css('overflow', 'hidden');
        //        window.scrollTo(scrollPosition[0], scrollPosition[1]);
        //    } else {
        //        $(".headertop-box").animate({
        //            right: "-270px"
        //        }, 400);
        //        $(this).addClass("isdrag").removeClass("drag-toggle");
        //        $('.mask2').remove();

        //        // un-lock scroll position
        //        var html = jQuery('html');
        //        var scrollPosition = html.data('scroll-position');
        //        html.css('overflow', html.data('previous-overflow'));
        //        window.scrollTo(scrollPosition[0], scrollPosition[1])
        //    }
        //    return false;
        //});
        if ($(window).width() > 767) {
            $(function () {
                $.scrollify({
                    section: ".section-class-name",
                    sectionName: "section-name",
                    updateHash: true,
                    before: function (index) {
                        $("#clickgo_menu li").removeClass("active");
                        $("#clickgo_menu li[index-scroll='" + index + "']").addClass("active");
                    },
                });
                $("#clickgo_menu li a,#getstarted,#logo,.btnForContct").click(function () {                    
                    if ($(this).closest(".btnForContct").length > 0)
                        $("#FreeTextSubject").val($(this).html());
                    else
                        $("#FreeTextSubject").val("");
                    var Scroll = $(this).parent().attr("name");
                    $.scrollify.move("#" + Scroll);
                })
            });
        }
    </script>
</body>

</html>

SPA/Views/Shared/ClickGo_Footer.cshtml
@{
    List<SPA.Models.LanguageNewShop> Language = ViewBag.Language;
    Language = Language.Where(c => c.Page_Name == "Layout_Footer").ToList();
    int LanguageId = ViewBag.LangId;
}
    <div class="clickGo_footer">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h4>@*Reach Us Anytime*@ @Language.Where(c => c.Order_id == 10).Select(c => c.Value).FirstOrDefault()</h4>
                <ul>
                    @*<li><a href="" style="color:#fff">Contact Us</a></li>*@
                    <li>info@click-and-go.ch</li>
                    @*<li><a><img src="~/images/click/googleplay.png" /></a></li>*@
                </ul>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h4>@*Discover*@ @Language.Where(c => c.Order_id == 11).Select(c => c.Value).FirstOrDefault()</h4>
                <ul>
                    <li>@*How does CLICK-AND-GO work?*@ <a href="/clickandgo?Lang=@LanguageId#Wie"> @Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault()</a></li>
                    <li>@*Why CLICK-AND-GO?*@ <a href="/clickandgo?Lang=@LanguageId#Warum"> @Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault()</a></li>
                    <li>@*FAQ‘S*@ <a href="/clickandgo?Lang=@LanguageId#FAQ"> @Language.Where(c => c.Order_id == 5).Select(c => c.Value).FirstOrDefault()</a></li>
                </ul>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8">
                <h4>@*ABOUT US*@ @Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault()</h4>
                <ul>
                    <li>@*Conditions of Use*@<a href="/Aboutus?Lang=@LanguageId#AGB"> @Language.Where(c => c.Order_id == 6).Select(c => c.Value).FirstOrDefault()</a></li>
                    <li>@*Data protection*@ <a href="/Aboutus?Lang=@LanguageId#Datenschutz">@Language.Where(c => c.Order_id == 7).Select(c => c.Value).FirstOrDefault()</a></li>
                    <li><a href="/ClickGo/Impressum?lang=@LanguageId" >@*Impressum*@ @Language.Where(c => c.Order_id == 9).Select(c => c.Value).FirstOrDefault()</a></li>
                </ul>
            </div>
            @*<div class="col-lg-9 col-md-9 col-sm-9">
                <h4>Subscribe to the newsletter</h4>
                <div class="input-group" style="margin-top: 1vw;">
                    <input type="text" class="form-control footer_text" placeholder="click and type your email here and press enter" style="height: 5vh;">
                    <span class="input-group-addon footer_arrow"><i class="fa fa-arrow-right" aria-hidden="true"></i></span>
                </div>
            </div>*@
        </div>
    </div>


SPA/Views/Shared/Freecustomer_Layout.cshtml
<ul class="progressbar Freecustomer_process">
    <li class="col-lg-8 col-md-8 col-sm-8 col-xs-8" id="InfoPage">Info</li>
    <li class="col-lg-8 col-md-8 col-sm-8 col-xs-8" id="EmployeePage">Employee</li>
    <li class="col-lg-8 col-md-8 col-sm-8 col-xs-8" id="ThankPage">Thank You</li>
</ul>

SPA/Views/Shared/_ClickFooter.cshtml
@model IEnumerable<SPA.Language_NewShop>
@{ 
    List<Language_NewShop> Language = Model.ToList();
    Language = Language.Where(c => c.Page_Name == "Layout_Footer").ToList();
}
@Scripts.Render("~/bundles/bootstrap")
<!--Footer Start-->
<footer>
    <div>
        <ul>
            <li class="col-lg-12 col-md-12 col-sm-12 no-padding">
                <div class="bg1">
                    <h3 class="swp-ttl2">@Html.Raw(Language.Where(c => c.Order_id == 1).Select(c => c.Value).FirstOrDefault())@*SMARTWARE PLUSE*@</h3>
                </div>
                <ul class="footer-list" id="Menu-page">
                    <li><a class="jump" name="/SMARTWAREPLUS#Wie" style="cursor:pointer" @*href="/Home/SMARTWAREPLUS#Wie"*@>@Html.Raw(Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault())@*Wie funktioniert SmartWarePlus?*@</a></li>
                    <li><a class="jump" name="/SMARTWAREPLUS#Warum" style="cursor:pointer" @*href="/Home/SMARTWAREPLUS#Warum"*@>@Html.Raw(Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault())@*Warum SmartWarePlus?*@</a></li>
                    <li><a name="/SMARTWAREPLUS#FAQ" style="cursor:pointer" @*href="/Home/SMARTWAREPLUS#FAQ"*@>@Html.Raw(Language.Where(c => c.Order_id == 5).Select(c => c.Value).FirstOrDefault())@*FAQ'S*@</a></li>
                </ul>
            </li>

            <li class="col-lg-12 col-md-12 col-sm-12 no-padding">
                <div class="bg1">
                    <h3 class="swp-ttl2">@Html.Raw(Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault())@*ABOUT US*@</h3>
                </div>
                <ul class="footer-list" id="Menu-page">
                    <li><a name="/About#AGB" style="cursor:pointer" @*href="/Home/About#AGB"*@>@Html.Raw(Language.Where(c => c.Order_id == 6).Select(c => c.Value).FirstOrDefault())@*AGB's*@</a></li>
                    <li><a name="/About#Datenschutz" style="cursor:pointer" @*href="/Home/About#Datenschutz"*@>@Html.Raw(Language.Where(c => c.Order_id == 7).Select(c => c.Value).FirstOrDefault())@*Datenschutz*@</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <img src="~/images/click/swiss.png" alt="" class="pull-right mb5 mr30" />
    <div class="clearfix"></div>

    <div class="swp-res bg1">
        <span>@Html.Raw(Language.Where(c => c.Order_id == 8).Select(c => c.Value).FirstOrDefault()) &nbsp;&nbsp;all rights reserved </span>
    </div>
</footer>

        <!--End Footer-->
        @if (ViewBag.LangId == 1)
        {
            <script>
                $("#LangChange #English a").addClass("activeShop");
            </script>
        }
        @if (ViewBag.LangId == 2)
        {
            <script>
                $("#LangChange #German a").addClass("activeShop");
            </script>
        }
        @if (ViewBag.LangId == 3)
        {
            <script>
                $("#LangChange #French a").addClass("activeShop");
            </script>
        }

SPA/Views/Shared/_Footer.cshtml
@using SPA.Models
@{
    SPA.Models.ShopMasterDetail LendingInfo = ViewBag.lendingDetails;
    List<SPA.Models.LendingWeekScheduleDetails> WeekDetails = new List<SPA.Models.LendingWeekScheduleDetails>();
    WeekDetails = ViewBag.WeekDetails;
    List<SPA.Models.LanguageLabelDetails> LanguageDetail = ViewBag.Language;
    var Language = LanguageDetail.Where(c => c.Page_Name == "Lending_Page").ToList();
    var DayLangList = LanguageDetail.Where(c => c.Page_Name == "Create_Employee").ToList();
    var Closed = Language.Where(c => c.Order_id == 41).FirstOrDefault();
    var StatusClosed = Closed.Value;
    var EnLabelStatusClosed = Closed.English_Label;


}
<footer>
    <div class="Footer-Box" id="FooterBox">
        <div class="col-lg-7 col-md-7 col-sm-6">
            <h4 class="footer-heading margin-bottom10">@*GET IN TOUCH*@ @Language.Where(c => c.Order_id == 32).Select(c => c.Value).FirstOrDefault()</h4>
            <div class="footer-Getin">
                @Html.Action("Contact", "Footer");
            </div>
        </div>
        <div class="col-lg-7 col-md-7 col-sm-6">
            <h4 class="footer-heading margin-bottom10">@*CONTACT US*@ @Language.Where(c => c.Order_id == 33).Select(c => c.Value).FirstOrDefault()</h4>
            <div class="footer-Contact">
                <div class="footer-address">
                    <span class="footer-icon"><i class="fa fa-home" aria-hidden="true"></i></span>
                    <ul>
                        @*<li>Platform Doctor and Spa Directory Kappelergasse 1</li>
                            <li>563010</li>
                            <li>U.S.A</li>*@
                        <li id="FooterAddress">@(!string.IsNullOrEmpty(LendingInfo.Address) ? LendingInfo.Address : LendingInfo.Shop_Address)</li>
                        <li><span id="FooterZipCode">@(!string.IsNullOrEmpty(LendingInfo.ZipCode) ? LendingInfo.ZipCode : LendingInfo.Shop_ZipCode)</span>&nbsp;<span id="FooterShopCity">@(!string.IsNullOrEmpty(LendingInfo.ShopCity) ? LendingInfo.ShopCity : LendingInfo.Shop_ShopCity)</span></li>
                        <li>@LendingInfo.country</li>
                    </ul>
                </div>
                <div class="footer-address margin-top15">
                    <span class="footer-icon"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                    <ul>
                        <li id="FooterEmailId">@*info@spa.com*@ @(!string.IsNullOrEmpty(LendingInfo.Email_id) ? LendingInfo.Email_id : LendingInfo.Shop_Email_id) @*ShopDetails.CCTSP_User.Select(c=>c.EmailId).FirstOrDefault()*@</li>
                    </ul>
                </div>
                <div class="footer-address margin-top15">
                    <span class="footer-icon"><i class="fa fa-phone" aria-hidden="true"></i></span>
                    <ul>
                        <li id="FooterPhoneNo">@*+4412141564*@ @*@ShopDetails.CCTSP_User.Select(c => c.PhoneNo).FirstOrDefault()*@ @(!string.IsNullOrEmpty(LendingInfo.PhoneNo) ? LendingInfo.PhoneNo : LendingInfo.Shop_PhoneNo)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10">
            <h4 class="footer-heading margin-bottom10">@*SCHEDULE*@ @Language.Where(c => c.Order_id == 34).Select(c => c.Value).FirstOrDefault()</h4>
            <div class="footer-schedule table-responsive">
                <table class="table">
                    <tbody id="MainWeekSchedule">
                        @foreach (var item in WeekDetails)
                        {
                            <tr>
                                <td><i class="fa fa-clock-o footer-icon" aria-hidden="true"></i><span>@item.Day</span></td>
                                <td>@(item.Catgdesc != null && item.Catgdesc != EnLabelStatusClosed ? item.Catgdesc : StatusClosed)</td>
                                <td>@(item.Gender != null && item.Gender != EnLabelStatusClosed ? item.Gender : StatusClosed)</td>
                            </tr>
                        }
                    </tbody>
                </table>
                @*<ul id="MainWeekSchedule">
                        @foreach (var item in Model.OrderBy(c=>c.CatgTypeid).ToList())
                        {
                            <li> @item.Day   @(item.CatgDesc!=null?item.CatgDesc:"Closed")</li>
                        }
                    </ul>*@
                @*<ul>
                            <li id="DaySchedule"> @(LendingInfo.FromDay != null? LendingInfo.FromDay+"-":"Monday-")@(LendingInfo.ToDay != null ? LendingInfo.ToDay:"Sunday")</li>
                            <li id="TimeSchedule"> @(LendingInfo.ShopStartTime != null?LendingInfo.ShopStartTime+"AM to":"09:00 AM to ") @(LendingInfo.ShopEndTime!= null ?LendingInfo.ShopEndTime+"PM":"09:00 PM")</li>
                    </ul>*@
            </div>
        </div>
        <div class="clearfix"></div>

    </div>
    <div class="footer-line text-center row">
        @*2016 All Rights Reserved # CLICK-AND-GO*@ @Language.Where(c => c.Order_id == 35).Select(c => c.Value).FirstOrDefault()
    </div>
</footer>

SPA/Views/Shared/_LangValidation.cshtml
<script type="text/javascript" src="@Model"></script>

SPA/Views/Shared/_LoderPage.cshtml
<div class="loader" id="loader" style="display:none;">
    <img src="~/images/@(Model>=3?"Doctor_Loader3.gif":"SPALOADER.gif")" />
</div>

SPA/Views/Shared/_Message.cshtml

@{ 
    string Msg = Model;
    Session["Message"] = "";
}
 <!-- Welcome modal start-->
<div class="welcome-modal">
    <div id="MessageModel" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body margin-bottom30" id="MessageModelAlert">
                    <h1 class="text-center margin-bottom30"><span>CLICK-AND-GO</span></h1>
                    <p class="title15 text-center margin-bottom30">@Msg</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Welcome modal End-->
<script>
    $('#MessageModel').modal("show");
</script>

SPA/Views/Shared/_ProcessHead.cshtml
@using System.Configuration
@using SPA.Common
@{
    ViewBag.Title = "_ProcessHead";
    int schlId = Convert.ToInt32(ConfigurationManager.AppSettings["ApplicationVariable"]);
    cctspDatabaseEntities22 SPA = new cctspDatabaseEntities22();
    var link = System.Web.HttpContext.Current.Request.Url.Host;
    Function fu = new Function();
    schlId = Convert.ToInt32(fu.GetShopId(link));
    List<Language_Label_Detail> Language = new List<Language_Label_Detail>();
    int LanguageId = SPA.CCTSP_SchoolMaster.Where(c => c.ActiveStatus == "A" && c.SchlId == schlId).Select(c => c.Lang_id).FirstOrDefault().Value;
    Language = SPA.Language_Label_Detail.Where(c => c.Page_Name == "Reservation_Row" && c.Lang_id == LanguageId).ToList();
}
<ul class="progressbar full-width">
    <li class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="a1">@Language.Where(c => c.Order_id == 2).Select(c => c.Value).FirstOrDefault()@*Choose your Product*@</li>
    <li class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="a2">@Language.Where(c => c.Order_id == 1).Select(c => c.Value).FirstOrDefault()@*Login*@</li>
    <li class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="a3">@Language.Where(c => c.Order_id == 3).Select(c => c.Value).FirstOrDefault()@*Choose your employee, date and time*@</li>
    <li class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="a4">@Language.Where(c => c.Order_id == 4).Select(c => c.Value).FirstOrDefault()@*Confirm the Booking*@</li>
</ul>

